from django.urls import path
from . import views

urlpatterns = [
    path('', views.log, name='log'),
    path('logn', views.logn, name='logn'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('userhome', views.userhome, name='userhome'),
    path('registre', views.registre, name='registre'),
    path('reg', views.reg, name='reg'),
    path('usnchk', views.usnchk, name='usnchk'),
    path('pwdchk', views.pwdchk, name='pwdchk'),
    path('viewusers', views.viewusers, name='viewusers'),
    path('deluser/<int:id>', views.deluser, name='deluser'),
    path('gotoprof', views.gotoprof, name='gotoprof'),
    path('prof', views.prof, name='prof'),
    path('usnachk', views.usnachk, name='usnachk'),
    path('gotovp', views.gotovp, name='gotovp'),
    path('ditprof', views.ditprof, name='ditprof'),
    path('editprof', views.editprof, name='editprof'),
    path('gotocrrm', views.gotocrrm, name='gotocrrm'),
    path('createroom', views.createroom, name='createroom'),
    path('roomcheck', views.roomcheck, name='roomcheck'),
    path('viewroom', views.viewroom, name='viewroom'),
    path('gotoam/<int:id>', views.gotoam, name='gotoam'),
    path('addmembers', views.addmembers, name='addmembers'),
    path('gotorm/<int:id>', views.gotorm, name='gotorm'),
    path('delmembers', views.delmembers, name='delmembers'),
    path('ditroom/<int:id>', views.ditroom, name='ditroom'),
    path('editroom', views.editroom, name='editroom'),
    path('delroom/<int:id>', views.delroom, name='delroom'),
    path('goto', views.goto, name='goto'),
    path('createcon', views.createcon, name='createcon'),
    path('viewconn', views.viewconn, name='viewconn'),
    path('gotoconn/<int:id>', views.gotoconn, name='gotoconn'),
    path('gotocm/<int:id>', views.gotocm, name='gotocm'),
    path('sendchat', views.sendchat, name='sendchat'),
    path('createmod', views.createmod, name='createmod'),
    path('moder', views.moder, name='moder'),
    path('viewmod', views.viewmod, name='viewmod'),
    path('insta/<int:id>', views.insta, name='insta'),
    path('instachat', views.instachat, name='instachat'),
    path('gotofeedbk', views.gotofeedbk, name='gotofeedbk'),
    path('feed', views.feed, name='feed'),
    path('viewfeed', views.viewfeed, name='viewfeed'),
    path('pay', views.pay, name='pay'),
    path('charge', views.charge, name='charge'),
]
