# Generated by Django 3.2.4 on 2021-08-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
