# Generated by Django 3.2.4 on 2021-08-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('room_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='room_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.rooms')),
                ('usid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.register')),
            ],
        ),
        migrations.CreateModel(
            name='moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.rooms')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=9999999)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.rooms')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.profile')),
            ],
        ),
    ]
