# Generated by Django 3.2.4 on 2021-08-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0003_chats_moderators_room_members_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.profile')),
            ],
        ),
    ]
