# Generated by Django 3.2.4 on 2021-09-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0004_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='crid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cr.register'),
            preserve_default=False,
        ),
    ]
