# Generated by Django 3.2.4 on 2021-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0005_connections_crid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='moderator',
            field=models.CharField(max_length=50),
        ),
    ]
