# Generated by Django 3.2.4 on 2021-09-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_alter_moderators_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(max_length=500)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.register')),
            ],
        ),
    ]
